# Generated by Django 5.2.5 on 2025-09-26 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="El numero de telefono debe tener el formato: '+56' asopao.", regex='^\\+569\\d{8}$')], verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=30, unique=True, verbose_name='Correo Electronico')),
                ('direccion', models.CharField(blank=True, max_length=50, verbose_name='Direccion :')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion del contacto')),
            ],
        ),
    ]
