# Generated by Django 5.2.5 on 2025-09-27 00:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agendapersonal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message="El numero de telefono debe tener el formato: '+56' asopao.", regex='^\\+569\\d{8}$')], verbose_name='Teléfono'),
        ),
    ]
